### ISSUE TITLE
Schedule Mode 'Running'

### ISSUE THREAD

**Issue by csteenwyk** [Einstein42/udi-ecobee-poly#14]
I am trying to automate setting away/home.

To set away:
Set the 'Climate Type' to 'Away' with a 'Permanent' hold

To set home:
Set the 'Schedule Mode' to 'Running'

The log file outputs the following:
cmdSetScheduleMode: CLISMD=0 already set to 0

I have tried first setting the 'Schedule Mode' to 'Hold Next' with no success.

**Comment by jimboca** [comment]
You are running 2.0.10 right? I thought I fixed that ☹️

**Comment by jimboca** [comment]
Yes, the code get's confused.  I need to keep track of what the current scheduled climate type defaults are and set the hold's for those that are different.

**Comment by csteenwyk** [comment]
Yeah, 2.0.10

**Comment by csteenwyk** [comment]
Saw the update, seems to be fixed
