### ISSUE TITLE
Couldn't update driver to ISY. StatusCode 404

### ISSUE THREAD

**Issue by richl007** [Einstein42/udi-ecobee-poly#19]
What am I doing wrong?

**Comment by richl007** [comment]
What am I doing wrong?

**Comment by jimboca** [comment]
I assume this is with poly cloud? If so that's and issue with PGC and hopefully will be resolved soon.

**Comment by jimboca** [comment]
This is a Polyglot Cloud issue https://github.com/UniversalDevicesInc/pgc/issues/7
