### ISSUE TITLE
https://polyglot.isy.io not upgrading to latest version when starting and stopping

### ISSUE THREAD

**Issue by psmith3** [Einstein42/udi-ecobee-poly#22]
Hi,

I see there is version 2.0.18 in the store on https://polyglot.isy.io. My current dashboard shows 2.0.17 running. If I stop and start the service, the log shows 2.0.18 but the dashboard still says I am running 2.0.17. Am I really on 2.0.18 or do I need to delete the node and reinstall from the store? Following the instructions on the store to just start and stop. I also see the readme of this project under Upgrading, says there is an option to Upgrade from the store, but I do not see that.

This is what I see in the log.
`1/5/19 11:18:14:062 [NodeServer][INFO ] :: check_profile: profile_info={'version': '2.0.18'} customData={'tokenData': {'access_token': '(removed for public post)', 'refresh_token': '(removed for public post)', 'expires': '2019-01-05T17:57:29', 'token_type': 'Bearer', 'expires_in': 3599, 'scope': 'smartWrite'}, 'profile_info': {'version': '2.0.18'}, 'climates': {'511896177939': [{'name': 'Away', 'ref': 'away'}, {'name': 'Sleep', 'ref': 'sleep'}, {'name': 'Home', 'ref': 'home'}], '411969173366': [{'name': 'Home', 'ref': 'home'}, {'name': 'Away', 'ref': 'away'}, {'name': 'Sleep', 'ref': 'sleep'}], '411927311944': [{'name': 'Home', 'ref': 'home'}, {'name': 'Away', 'ref': 'away'}, {'name': 'Sleep', 'ref': 'sleep'}]}}
`

**Comment by jimboca** [comment]
Sounds like you are running the cloud version? Cloud is brand new and not fully documented yet. There is no upgrading on the cloud, stop and restart grabs the latest version, but there's a bug in Polyglot Could where the version shown on the web page doesn't update. You can view the log and see that the latest is used.

**Comment by psmith3** [comment]
Thanks @jimboca . Yes, that is what I see in the log and thought that the web is not updating it. I guess that is a bug that needs to be filed if not already. Will look.

**Comment by jimboca** [comment]
It wasn't in the list, so I added it https://github.com/UniversalDevicesInc/pgc/issues/10

**Comment by psmith3** [comment]
Thanks
