### ISSUE TITLE
Issue with custom climate names

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-ecobee-poly#32]
The below shows that smart2 is not in the list, so that messes up the ordering.  Need to order them by the 'smart>n>' names.

@jimboca  I need to correct my previous statement that custom climates names are fixed for me. To test I manually set a custom climate from the admin console and the correct name came up and I thought it was fixed, I didn't notice that the settings for that name were wrong and next time a custom climate was set from the regular schedule I noticed the name was wrong again. I'm running cloud 2.0.26 and have pasted the discover climates line from the log below. Note that there is no smart2 defined. I'm not sure why, maybe it's a custom climate that I deleted in the past. I tried adding a new test custom and it added as smart5. The custom names and smart(n) names are correct below, however any custom climate setting >2 displays with an offset of +1 in the ISY, i.e., I'm running office PM now and the ISY shows as test.

discover: climates={'311054229478': [{'name': 'Away', 'ref': 'away'}, {'name': 'Home', 'ref': 'home'}, {'name': 'Sleep', 'ref': 'sleep'}, {'name': 'Office AM', 'ref': 'smart1'}, {'name': 'Karen dress', 'ref': 'smart3'}, {'name': 'Office PM', 'ref': 'smart4'}, {'name': 'test', 'ref': 'smart5'}]

Take a look when you get a chance, it's not critical and not sure if anyone else is seeing the problem, but wanted to give you more details.

**Comment by jimbo** [comment]
Hi. 😅

**Comment by jimboca** [comment]
> Hi. 😅

Sorry @jimbo I copy/pasted from a forum where I am jimbo but on here I am not :)

**Comment by jimboca** [comment]
All fixed
