### ISSUE TITLE
Sensor regression

### ISSUE THREAD

**Issue by cswelin** [Einstein42/udi-ecobee-poly#41]
Haven't checked my Polyglot in a while but noticed switches that act as sensor no longer appear, this is due to switches not having a `code`. Looks like #12 may have broke it.

Data its trying to parse:
`{'name': 'Bathroom', 'type': 'switch_plus', 'id': 'ls1w:255', 'capability': [{'type': 'temperature', 'id': '1', 'value': '699'}, {'type': 'occupancy', 'id': '2', 'value': 'true'}], 'inUse': False}`

**Comment by jimboca** [comment]
Sorry, I never saw this. I don't have any switches to test this but can attempt to fix it when I get a chance.

**Comment by cswelin** [comment]
No worries, to be honest, you don't need to fix it anymore. Switch+ wont be used as a sensor anymore.

Closing issue :)
