### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by richl007** [Einstein42/udi-ecobee-poly#43]
i get errors when i try to install

https://drive.google.com/open?id=1eZFWNGAOOCHKhoh1fC8C6YN_Igr3wjQd

**Comment by jimboca** [comment]
Please attach or paste log here for reference or post error message to the forum

**Comment by richl007** [comment]
createService: Error: (HTTP code 500) server error - rpc error: code = Unknown desc = name conflicts with an existing object at /app/node_modules/docker-modem/lib/modem.js:257:17 at getCause (/app/node_modules/docker-modem/lib/modem.js:287:7) at Modem.buildPayload (/app/node_modules/docker-modem/lib/modem.js:256:5) at IncomingMessage. (/app/node_modules/docker-modem/lib/modem.js:232:14) at IncomingMessage.emit (events.js:202:15) at IncomingMessage.EventEmitter.emit (domain.js:446:20) at endReadableNT (_stream_readable.js:1132:12) at processTicksAndRejections (internal/process/next_tick.js:76:17)
×

**Comment by jimboca** [comment]
Sorry, I have no idea how to run Polyglot in docker, there are some trying to do it but I've not followed the thread on the forum
