### ISSUE TITLE
Admin Console will Freeze if I click on Programs

### ISSUE THREAD

**Issue by gregkinney** [Einstein42/udi-ecobee-poly#58]
If the ecobee nodeserver is running and I click on the programs tab in the admin console, the programs will not load and admin console will eventually crash.

**Comment by exking** [comment]
not a poly issue

**Comment by gregkinney** [comment]
If I stop the ecobee poly, I have no issues. If I start the ecobee poly, then admin will crash. So this is not a poly issue?

**Comment by jimboca** [comment]
Please report to support@universal-devices.com and let them know your firmware and AC version from the about menu.
