### ISSUE TITLE
Ecobee disappeared off Nodeserver Store

### ISSUE THREAD

**Issue by macjeff** [Einstein42/udi-ecobee-poly#59]
I assume its intentional but went to get the new .28 update and its gone.

**Comment by jimboca** [comment]
It was only released to test, not production yet.

**Comment by macjeff** [comment]
There is currently no Ecobee on the Polisy or PGC nodeserver.  Not even the older version.

**Comment by jimboca** [comment]
In test mode it turns off others until it's released.
