### ISSUE TITLE
Changing setpoint when program running changes the actual "comfort setting"

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-ecobee-poly#6]
Changing setpoint when program running changes the actual "comfort setting" - so this is saved permanently moving forward

**Comment by jimboca** [comment]
@Einstein42 Looking at the code, it seems this was intentional?  It changes the setpoint for the currently running program.  This doesn't seem correct?  If the user is changing a setpoint then it's a temporary change, not a permanent one for the program?

The current code changes setpoint like this: https://www.ecobee.com/home/developer/api/examples/ex11.shtml

The user request is that it only modifies the current temperature, like so:
https://www.ecobee.com/home/developer/api/examples/ex5.shtml

But then we will have to track that we added the hold, and if they change it again we remove that hold and add the new one?

**Comment by Einstein42** [comment]
Good question, probably why I didn't know what to do there.
