### ISSUE TITLE
Ecobee Nodeserver not in Polyglot Cloud Store

### ISSUE THREAD

**Issue by tko85** [Einstein42/udi-ecobee-poly#66]
The Ecobee Nodeserver doesn't appear in the Polyglot Cloud Store.

**Comment by jimboca** [comment]
It is currently preparing for a new release which removes it from the store. Sorry, Nothing I can do about that. Hopefully will release soon.

**Comment by jimboca** [comment]
Version 2.2.0 released, should be available soon
