### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by JCBond** [Einstein42/udi-ecobee-poly#68]
I recently did a clean install of Polyglot onto a clean install of RPi. All running latest versions of software.

I have been using Ecobee Poly for years and other than the occasional reauthorize it has been working properly. On this new installation. I am seeing that the Ecobee Poly runs every 3 minutes. I see on the notes that that is a limitation imposed by Ecobee.

The issue I am having is that whenever I tell the system to change the MODE from OFF to AUTO, COOL, or HEAT. Nothing happens. The thermostat does not update.

I am happy to send longs, but I see that the logs contain tokens so I would not like to post these publicly.

**Comment by jimboca** [comment]
When you say you are changing mode, is that directly on the thermostat or from the ISY? The 3 minutes is how often the NS can query the ecobee servers to check for updates, but making a change from the ISY should happen immediately. If not email me the log package.

**Comment by JCBond** [comment]
When I make changes on ISY the changes do not get sent to the Thermostat. I just emailed you the log package. Any assistance would be greatly appreciated.

**Comment by JCBond** [comment]
I am looking at the ISY log and noticing that when I manually make a change on the ISY moving the Setpoint UP or DOWN using the buttons at the bottom. That is sent to the Thermostat instantly. But changing any of the parameters, like MODE, nothing happens in the LOG, it is like I didn't make any changes.

**Comment by jimboca** [comment]
When you change the mode in the pull down, you then click the "Mode" button to the left of the pulldown, right?  Older versions of Admin console did not require this, but it changed in recent versions.

**Comment by JCBond** [comment]
Now I feel stupid. I did not know or remembered that. I guess it is working. Sorry to have wasted your time.

**Comment by jimboca** [comment]
Haha, no worries, it annoys me many times as well that it was changed.
