### ISSUE TITLE
Setting 'Climate Type' sets hold as indefinite, should it use nextTransition?

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-ecobee-poly#9]
```
2018-12-11 21:21:21,635 [Controller] [INFO ] Posting Update Data for Thermostat 411956665463
2018-12-11 21:21:21,636 [Controller] [DEBUG] Post Data : {
  "functions": [
    {
      "params": {
        "holdClimateRef": "home",
        "holdType": "indefinite"
      },
      "type": "setHold"
    }
  ]
}
```

**Comment by jimboca** [comment]
It will now use the current set "Schedule Mode"

**Comment by ScarecrowFL** [comment]
Hi. I noticed that when I set a comfort mode (climate mode), and I set the hold type to indefinite, the thermostat still only holds until next transition.

**Comment by jimboca** [comment]
> Hi. I noticed that when I set a comfort mode (climate mode), and I set the hold type to indefinite, the thermostat still only holds until next transition.

This is the old PG2 node server, I added a issue for the current version: https://github.com/UniversalDevicesInc-PG3/udi-poly-ecobee/issues/10
